language: node_js
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo $PATH
install:
  - yarn install
script:
  - yarn build
  - yarn format
  - yarn lint
  - yarn test
